version: 1
disable_existing_loggers: false

formatters:
  json:
    format: "%(asctime)s %(levelname)s %(message)s %(process)s %(threadName)s %(name)s %(filename)s %(module)s %(funcName)s %(lineno)d"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: json

root:
  level: INFO
  handlers: [console]
